# Generated by Django 4.0.2 on 2022-06-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_category_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.CharField(default=str, max_length=200),
            preserve_default=False,
        ),
    ]
